#!/usr/bin/env python3
"""
check_availability_browser.py
-----------------------------
Robust version that drives a REAL Chromium browser (via Playwright) to check
where "Natch Thai Dry Mango Slices: Chili" is in stock on Swiggy Instamart
across 30 Hyderabad areas.

WHY A BROWSER?
  Swiggy is protected by AWS WAF, whose token is generated by JavaScript that
  a plain `requests` client cannot run — hence the 403s. A real browser passes
  the WAF naturally. We then call Swiggy's search API from *inside* the page
  (page.evaluate) with each area's lat/lng, so every request carries a valid
  token + your session cookies.

SETUP (run once):
    pip install playwright browser-cookie3
    playwright install chromium

RUN:
    # Easiest — auto-load cookies from your Chrome profile:
    python check_availability_browser.py

    # Or use the same cookies.txt file as the other script:
    python check_availability_browser.py --cookies-file cookies.txt

    # Watch it work (open a visible window):
    python check_availability_browser.py --headed
"""

import argparse
import sys
import time

# Reuse the shared helpers from the requests-based script.
from check_availability import (
    HYDERABAD_LOCATIONS,
    PRODUCT_SEARCH_TERM,
    PRODUCT_KEYWORDS,
    find_product,
    is_in_stock,
    parse_cookie_string,
    load_cookies_from_browser,
    load_cookies_from_env,
)

# JavaScript that runs INSIDE the browser page. It loops over every location
# and fetches the Instamart search API with that area's lat/lng. Because the
# fetch originates from the real, WAF-cleared page, it succeeds where requests
# gets a 403 — and the lat/lng params give us genuine per-location results.
JS_CHECK_LOCATIONS = """
async ({ locations, searchTerm }) => {
    const delay = ms => new Promise(r => setTimeout(r, ms));
    const results = [];

    for (const loc of locations) {
        const url = new URL("/api/instamart/search", "https://www.swiggy.com");
        url.searchParams.set("query", searchTerm);
        url.searchParams.set("pageNumber", "0");
        url.searchParams.set("layoutId", "3128");
        url.searchParams.set("pageType", "INSTAMART_SEARCH");
        url.searchParams.set("isPreSearchTag", "false");
        url.searchParams.set("queryUniqueId", "");
        url.searchParams.set("lat", String(loc.lat));
        url.searchParams.set("lng", String(loc.lng));
        url.searchParams.set("storeType", "INSTAMART");

        try {
            const resp = await fetch(url.toString(), {
                method: "GET",
                credentials: "include",
                headers: {
                    "Accept": "application/json, text/plain, */*",
                    "x-requested-with": "XMLHttpRequest",
                },
            });
            if (!resp.ok) {
                results.push({ name: loc.name, http_error: resp.status });
            } else {
                const data = await resp.json();
                results.push({ name: loc.name, data: data });
            }
        } catch (e) {
            results.push({ name: loc.name, exception: e.toString() });
        }
        await delay(800);
    }
    return results;
};
"""


def load_cookies(args) -> dict:
    if args.cookies_file:
        return parse_cookie_string(open(args.cookies_file).read().strip(),
                                   f"file {args.cookies_file}")
    if args.cookies:
        return parse_cookie_string(args.cookies, "--cookies flag")
    return load_cookies_from_browser() or load_cookies_from_env()


def to_playwright_cookies(cookies: dict) -> list:
    return [
        {"name": k, "value": v, "domain": ".swiggy.com", "path": "/"}
        for k, v in cookies.items()
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description="Browser-driven Swiggy availability check")
    parser.add_argument("--cookies-file", metavar="FILE")
    parser.add_argument("--cookies", metavar="COOKIE_STRING")
    parser.add_argument("--headed", action="store_true",
                        help="Show the browser window instead of running headless")
    args = parser.parse_args()

    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("\n  ERROR: Playwright is not installed. Run:\n"
              "      pip install playwright\n"
              "      playwright install chromium\n")
        return 1

    print("=" * 64)
    print("  Natch Thai Dry Mango Slices: Chili — Hyderabad Availability")
    print("  (browser-driven — defeats Swiggy's WAF)")
    print("=" * 64)

    print("\nLoading Swiggy session cookies …")
    cookies = load_cookies(args)
    if not cookies:
        print("  ERROR: No cookies found. Pass --cookies-file cookies.txt or log into "
              "swiggy.com in Chrome first.")
        return 1

    with sync_playwright() as p:
        print("Launching Chromium …")
        browser = p.chromium.launch(headless=not args.headed)
        context = browser.new_context(
            user_agent=("Mozilla/5.0 (Linux; Android 15; Pixel 9) "
                        "AppleWebKit/537.36 (KHTML, like Gecko) "
                        "Chrome/149.0.0.0 Mobile Safari/537.36"),
            locale="en-IN",
            timezone_id="Asia/Kolkata",
            geolocation={"latitude": HYDERABAD_LOCATIONS[0]["lat"],
                         "longitude": HYDERABAD_LOCATIONS[0]["lng"]},
            permissions=["geolocation"],
        )
        context.add_cookies(to_playwright_cookies(cookies))
        page = context.new_page()

        print("Warming up session (loading Instamart, clearing WAF challenge) …")
        try:
            page.goto("https://www.swiggy.com/instamart",
                      wait_until="domcontentloaded", timeout=45000)
        except Exception as e:
            print(f"  Warning during load: {e}")
        time.sleep(6)  # give the WAF JS challenge time to resolve

        print(f"\nChecking {len(HYDERABAD_LOCATIONS)} Hyderabad areas "
              "(running from inside the browser, ~1 min) …\n")
        raw_results = page.evaluate(
            JS_CHECK_LOCATIONS,
            {"locations": HYDERABAD_LOCATIONS, "searchTerm": PRODUCT_SEARCH_TERM},
        )
        browser.close()

    # ── Classify ──────────────────────────────────────────────────────────────
    available, out_of_stock, not_listed, errors = [], [], [], []
    for entry in raw_results:
        name = entry["name"]
        if "http_error" in entry:
            print(f"  {name:<22}  ERROR ({entry['http_error']})")
            errors.append((name, str(entry["http_error"])))
        elif "exception" in entry:
            print(f"  {name:<22}  EXCEPTION: {entry['exception'][:60]}")
            errors.append((name, entry["exception"][:60]))
        else:
            item = find_product(entry["data"])
            if item is None:
                print(f"  {name:<22}  Product not listed")
                not_listed.append(name)
            elif is_in_stock(item):
                print(f"  {name:<22}  IN STOCK  ✓  [{item.get('name')}]")
                available.append(name)
            else:
                print(f"  {name:<22}  OUT OF STOCK  [{item.get('name')}]")
                out_of_stock.append(name)

    # ── Summary ───────────────────────────────────────────────────────────────
    print("\n" + "=" * 64)
    print("  RESULTS SUMMARY")
    print("=" * 64)
    if available:
        print(f"\n  ✓  IN STOCK at {len(available)} location(s):")
        for loc in available:
            print(f"       {loc}")
    else:
        print("\n  Product not found in stock at any checked location.")
    if out_of_stock:
        print(f"\n  –  OUT OF STOCK at {len(out_of_stock)} location(s):")
        for loc in out_of_stock:
            print(f"       {loc}")
    if not_listed:
        print(f"\n  ?  Not listed ({len(not_listed)}):")
        for loc in not_listed:
            print(f"       {loc}")
    if errors:
        print(f"\n  !  Errors ({len(errors)}):")
        for loc, err in errors:
            print(f"       {loc}: {err}")
    print()
    return 0 if available else 1


if __name__ == "__main__":
    sys.exit(main())
